config/routes.rb
Rails.application.routes.draw do
  
  root 'main_pages#home'

  get '/home' => 'main_pages#home'

  get '/help' => 'main_pages#help'

  get '/about' => 'main_pages#about'

  post '/clients' => 'main_pages#client_post'

  resources :main_pages

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_pages_controller.rb
class MainPagesController < ApplicationController
skip_before_action :verify_authenticity_token

  def home
  end

  def help
  end

  def about
  end

  def client
  end

  def client_post
	  @client = params[:client]
	  # params[:id] = @client[:name]
	  if (@client[:name]=='admin' && @client[:password]=='654321') ||
       (@client[:email]=='admin@email.com' && @client[:password]=='654321')
       @client[:name] = "admin" 
       @client[:email] = "admin@email.com" 
	     render 'client' and return
	     #render text: 'name - '+@client[:name]+' ,   email - '+@client[:email] and return
	  else 
	    flash.now[:error] = "You are not admin or interviewer"
      render 'home' # render text: 'INCORRECT'
	  end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_pages_helper.rb
module MainPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container-fluid">
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", home_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <li><%= link_to "About", about_path %></li>
           </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/main_pages/about.html.erb
<h1>ABOUT</h1>
<p>Program by Design IF060</p>

app/views/main_pages/client.html.erb
<h1>Aid Interviewer</h1>
<p>Name : <%= @client[:name] %> , email : <%= @client[:email] %></p>

app/views/main_pages/help.html.erb
<h1>HELP</h1>
<p>Can I help You?</p>

app/views/main_pages/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Aid Interviewer</title>
  </head>
  <body>
<h1 class='center' font-size='40px'>Aid Interviewer</h1>
</br></br>
<form class='center' accept-charset="UTF-8" action="/clients" method="post">
  <label> name : <input type="text" name="client[name]" value="" /></label> </br> </br>
  <!--label> email :    <input type="text" name="client[email]" value="" /> </label> </br> </br-->
  <label> password : <input type="password" name="client[password]" value="" size='16px' /></label> </br> </br>
  <div ><input  class="btn btn-lg btn-primary" type="submit" value='Log In' /></div>
</form>
</br></br></br>

  <!--%= link_to "Sign up now!", '#', class: "btn btn-lg btn-primary" %-->


<%= link_to image_tag("Interview_skills_logo.png", alt: "Aid Interviewer"), about_path %>

  </body>
</html>